allowBuilds:
  '@parcel/watcher': false
onlyBuiltDependencies:
  - esbuild

minimumReleaseAge: 2880 # ignore dependency updates released less than 2 days ago

minimumReleaseAgeExclude:
  - yawa-tracker@0.0.5
  - '@sveltejs/kit@2.68.0'
  - kyushu-types@0.2.1
  - '@sveltejs/vite-plugin-svelte@7.3.0'
  - cookie@0.7.0
  - brace-expansion@5.0.7 || 5.0.8 || 5.0.9
  - immutable@5.1.8
  - postcss@8.5.18 || 8.5.23
  - nanoid@3.3.16 || 3.3.17

overrides:
  brace-expansion@>=3.0.0 <5.0.7: ^5.0.7
  brace-expansion@>=3.0.0 <5.0.9: ^5.0.9
  brace-expansion@>=4.0.0 <5.0.8: ^5.0.8
  brace-expansion@>=4.0.0 <5.0.9: ^5.0.9
  cookie@<0.7.0: ^0.7.0
  immutable@>=5.0.0-beta.1 <5.1.8: ^5.1.8
  nanoid@<3.3.16: ^3.3.16
  nanoid@<3.3.17: ^3.3.17
  postcss@<=8.5.17: ^8.5.18
  postcss@<=8.5.22: ^8.5.23
