allowBuilds:
  '@parcel/watcher': false
onlyBuiltDependencies:
  - esbuild

minimumReleaseAge: 2880 # ignore dependency updates released less than 2 days ago

minimumReleaseAgeExclude:
  - yawa-tracker@0.0.4
  - '@sveltejs/kit@2.65.2'
  - cookie@0.7.0
  - brace-expansion@5.0.6

overrides:
  brace-expansion@>=5.0.0 <5.0.6: ^5.0.6
  cookie@<0.7.0: ^0.7.0
